@Library('jenkins-shared-library') _

pipeline {
    agent any

    environment {
        ECR_REPO_URL = "YOUR_ECR_REPO_URL"
        HELM_CHART_PATH = "./helm"
        RELEASE_NAME = "simple-java-app"
        NAMESPACE = "default"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Test') {
            steps {
                buildApp()
            }
        }
        stage('Docker Build and Push') {
            steps {
                dockerBuildAndPush(ECR_REPO_URL)
            }
        }
        stage('Deploy to EKS') {
            steps {
                deployToEKS(HELM_CHART_PATH, RELEASE_NAME, NAMESPACE)
            }
        }
    }
}
